from optimization_algorithms.coral_reef import CoralReefOptimization
from optimization_algorithms.artificial_bee_colony import ArtificialBeeColony
from optimization_algorithms.simulated_annealing import SimulatedAnnealing
from optimization_algorithms import func
